nelmio_cors:
    defaults:
        allow_origin: ['*']          # Allows any domain
        allow_credentials: false
        allow_headers: ['*']         # Allows any headers
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600

    paths:
        '^/':                        # Apply these rules to all paths
            allow_origin: ['*']       # Allows any domain for all requests
            allow_headers: ['*']      # Allows any headers
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
